service: sls-appsync-bookstore
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-1
plugins:
  - serverless-appsync-plugin
custom:
  appSync:
    name: bookStoreAppSyncApi
    authenticationType: AMAZON_COGNITO_USER_POOLS
    additionalAuthenticationProviders:
      - authenticationType: AWS_IAM
    userPoolConfig:
      awsRegion: ap-southeast-1
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - type: Query
        field: getBookById
        dataSource: booksTable
      - type: Query
        field: getRegistrationsById
        dataSource: registrationsTable
      - type: Query
        field: listBooks
        dataSource: booksTable
      - type: Query
        field: listRegistrations
        dataSource: registrationsTable
      - type: Mutation
        field: createBook
        dataSource: booksTable
      - type: Mutation
        field: createRegistrations
        dataSource: registrationsTable
    dataSources:
      - type: AMAZON_DYNAMODB
        name: booksTable
        config:
          tableName: !Ref booksTable
      - type: AMAZON_DYNAMODB
        name: registrationsTable
        config:
          tableName: !Ref registrationsTable

# add cloudformation resources here
resources:
  Resources: ${file(resources.yml)}
